### PR TITLE
Update workspaces item with plan for the day

### PR DESCRIPTION
**Pull request by nickmeinhold**
My original intention in writing this item was that the purpose of our column is to describe our day - current task and plan for the day.  This PR is an attempt to make that clearer.

### CODE REVIEW

**Review by T-Davis — DISMISSED** [review]
As always, thanks for keeping us (and the documentation) honest 👍

**Comment by nickmeinhold** [comment]
Thanks for the fix @T-Davis!  I tweaked the language a little, what do you think?

**Review by T-Davis — APPROVED** [review]
Much clearer! Approved 🥇

**Review by tamari-gray — APPROVED** [review]
lgtm :)

**Comment by tamari-gray** [comment]
could we add a test?

**Comment by nickmeinhold** [comment]
Thanks heaps guys!

**Pull request merged**
