### PR TITLE
i157: Add factory constructor to sub-problems

### LINKED ISSUE #157: Add a factory constructor for each sub-problems and bv_problem snippet

### PR DESCRIPTION
**Pull request by T-Davis**
fixes #157

### CODE REVIEW

**Comment by T-Davis** [comment]
Fixes #157

**Review by nickmeinhold — APPROVED** [review]
Thanks heaps Trev!

**Comment by nickmeinhold** [comment]
Couple of quick adminny type comments: 
- the PR titles should (imo) be quite short and snappy - the git history being easy to read is worth leaning toward brevity over clarity 
  - I took the liberty of editing the title, please let me know if that was going too far :-) 
- adding the "fixes #num" thing (I think) needs to be done in the main comment, ie. the first one, otherwise it doesn't link and close the issue 
- as a reviewer it's super helpful to have the author point out anything unexpected or anything that will save you time - the reason it comes to mind is the formatter creating whole lot of changes in this case is an example where communicating there was something unexpected would be quite helpful 
- anything that causes a lot of changes (like formatting, or renaming files, etc.) would ideally be done in a separate PR 
  - we have an item in the CoC to this effect I believe, not sure if it covers formatting specifically though 
  - personally I don't think it's worth pulling out the formatting into a separate PR at this point, just putting it out there for future PRs 

Thanks again mate, awesome work!!!

**Comment by T-Davis** [comment]
@nickmeinhold Thanks for the feedback! Those are all great points, I'll pay more attention in the future.
Sorry for the mess, next one will look good 👍

**Comment by nickmeinhold** [comment]
@T-Davis nothing to apologise for mate, bloody great work! 👍

**Review by tamari-gray — APPROVED** [review]
LGTM! beautiful work @T-Davis 🥇 

@nickmeinhold could i request you have a look aswell before she gets merged. Im not confident enough in built value to give quality input on this bootiful pr. 🙏

**Comment by nickmeinhold** [comment]
Thanks @tamari-gray! I approved it already but wanted to check if you wanted to review as well.  Looks like we're good to go!

**Pull request merged**
