### PR TITLE
Update middleware snippets

### LINKED ISSUE #51: Update middleware snippets
- [ ] Make the X in XService be lowercase in some places: 
```Dart 
SoAndSoMiddleware(XService xService)
```
and 
```Dart
final reaction = await xService.;
```

- [ ] add cursors for the variable and service function (put a cursor at each _ ):
```Dart 
final _1 = await authService._2;
store.dispatch(_1);
```

### PR DESCRIPTION
**Pull request by T-Davis**
Fixes #51

### CODE REVIEW

**Comment by nickmeinhold** [comment]
Looks awesome mate!  How would you feel about going out of scope because my dumass forgot about the imports?  More than happy to make a separate issue if you prefer!

**Comment by T-Davis** [comment]
> EDIT: don't mind me, I can't seem to resist being dum... definitely warrants a new issue with an explanation of what I mean, I'll do that now :-)

alg!

**Comment by nickmeinhold** [comment]
Cool, I made #118 for the imports.  @T-Davis did you mean to request a review on this PR?

**Review by nickmeinhold — APPROVED** [review]
I think this is great - the middleware is much nicer to use now!  Thanks heaps @T-Davis!!!

**Pull request merged**
